### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Justi811** [Justi811/furima-29723#9]
# フリマアプリのURL
https://furima-29723.herokuapp.com

# Basic認証情報
ID:admin
password:heroherokun

# 出品者情報
email:test100@gmail.com
password:Test100

# 出品者情報
email:test1000@gmail.com
password:Test1000

# 購入用カード情報
番号:4242424242424242
期限:4/24
cvc:123

## よろしくお願いいたします。

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by Justi811** [comment]
ご確認ありがとうございました。
